name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - id: Build-Deploy-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'EaseCation'
        reponame: 'mc-text-formater'
        token: ${{ secrets.GITHUB_TOKEN }}
        useyarn: true
    
